### ISSUE TITLE
Modern.ie local testing is redirecting to the home page when trying to generate a report

### ISSUE THREAD

**Issue by Yelnik** [MicrosoftEdge/static-code-scan#103] opened 2015-10-22 16:28 UTC
After it scans my local website, and comes up with the button to "Submit" the report, I am simply redirected to https://dev.modern.ie/

I have checked to ensure the form submits to "https" in the index.html, as I found this was a fix in other posts. It still doesn't work though.

**Comment by molant** [comment] 2015-10-22 16:32
Duplicate of https://github.com/MicrosoftEdge/static-code-scan/issues/96

**Closed by molant** 2015-10-22 16:32 UTC
Labels: duplicate

**Comment by Yelnik** [comment] 2015-10-22 16:34
You guys can't just put a form on the page that we can paste the results into?

**Comment by molant** [comment] 2015-10-22 16:40
It is in the backlog but at the moment there are items with a higher priority. The JSON file shouldn't be too complicated to read. If you have any question until we release this feature let me know.
