### ISSUE TITLE
Offline scan does not generate report- Page not found error

### ISSUE THREAD

**Issue by nambir** [MicrosoftEdge/static-code-scan#105] opened 2015-11-28 11:42 UTC
![edge- scan report- issue](https://cloud.githubusercontent.com/assets/16057911/11451644/0a3adc36-9608-11e5-951a-219313b27c7b.jpg)

Offline scan does not generate report- Page not found error.
Please check the attachment.

Report URL "https://dev.windows.com/en-us/microsoft-edge/report/local/"

**Comment by molant** [comment] 2015-11-30 22:57
Duplicate of #96

**Closed by molant** 2015-11-30 22:57 UTC
